version: "3.9"

networks:
  frontend:
  backend:

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./front/build:/var/www/html:delegated
    depends_on:
      - spring
      - npm
    ports:
      - 81:80
    networks:
      - frontend
      - backend

  spring:
    container_name: spring
    build:
      context: .
      dockerfile: docker/spring.dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://125.134.138.184:3306/blog?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: bamtol
      SPRING_DATASOURCE_PASSWORD: Bamtol1234!
    networks:
      - backend

  npm:
    container_name: node
    build:
      context: .
      dockerfile: docker/npm.dockerfile
    volumes:
      - ./front:/app
      - ./front/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - frontend
