version: "3.9"

networks:
  frontend:
  backend:

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./front/build:/var/www/html:delegated
    depends_on:
      - mysql
      - spring
      - npm
    ports:
      - 81:80
    networks:
      - frontend
      - backend
    
  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MARIADB_DATABASE: blog
      MARIADB_USER: test
      MARIADB_PASSWORD: test1234!
      MARIADB_ROOT_PASSWORD: test1234!
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3307:3307
    networks:
      - backend

  spring:
    container_name: spring
    build:
      context: .
      dockerfile: docker/spring.dockerfile
    platform: linux/amd64
    ports:
      - 8080:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/blog?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test1234!
    volumes:
      - ./backend/spring:/app
    depends_on:
      - mysql
    networks:
      - backend

  npm:
    container_name: node
    build:
      context: .
      dockerfile: docker/npm.dockerfile
    volumes:
      - ./front:/app
      - ./front/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - frontend