version: "3.9"

networks:
  backend:

services:
  spring:
    container_name: spring
    build:
      context: .
      dockerfile: dockerfiles/spring.dockerfile
    platform: linux/amd64
    # docker 파일 경로
    volumes:
      - ./spring:/app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blog?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test1234!
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    # 커맨드 종료 시 컨테이너 종료 방지
    tty: true
    ports: 
      - 3306:3306
    environment:
      MARIADB_DATABASE: blog
      MARIADB_USER: test
      MARIADB_PASSWORD: test1234!
      MARIADB_ROOT_PASSWORD: test1234!
    volumes:
      - ./mysql:/var/lib/mysql
      # docker에 저장된 mysql 정보가 나의 로컬 환경과 연동 (로컬 : 컨테이너)
    networks:
      - backend