openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v2
servers:
- url: http://125.134.138.184:8080/ # 변경
  description: bamtol Blog에 대한 api 규격입니다.
  
paths:
  
  /posts/{postId}:
    parameters:
    - name: postId
      in: path
      required: true
      schema:
        type: integer
        format: int32

    get:
      tags:
      - post-controller
      operationId: readPost
      description : "포스트 읽기 요청"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadPostDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                oneOf:
                - $ref: '#/components/schemas/ReadPostResponse'
    
    post:
      tags:
      - post-controller
      operationId: CreatePostResponse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePostDto'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                oneOf:
                - $ref: '#/components/schemas/CreatePostResponse'
    
    put:
      tags:
      - post-controller
      operationId: updatePost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePostDto'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                oneOf:
                - $ref: '#/components/schemas/UpdatePostResponse'
          
    delete:
      tags:
      - post-controller
      operationId: deletePost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletePostDto'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                oneOf:
                - $ref: '#/components/schemas/DeletePostResponse'
    patch:
      tags:
      - post-controller
      operationId: patchPost
      parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                oneOf:
                - $ref: '#/components/schemas/SignUpResponseDto'
        
  /auth/signup:
    post:
      tags:
      - auth-controller
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                oneOf:
                - $ref: '#/components/schemas/SignUpResponseDto'
                - $ref: '#/components/schemas/SignUpErrorResponse'

  /auth/login:
    post:
      tags:
      - auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/LoginDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                oneOf:
                - $ref: '#/components/schemas/LoginResponseDto'
                - $ref: '#/components/schemas/LoginErrorResponse'
                    
                  
components:

  schemas:
    LoginErrorResponse:
      type: object
      oneOf:
        - $ref: '#/components/schemas/InvalidEmailError'
        - $ref: '#/components/schemas/InvalidPasswordError'
    SignUpErrorResponse:
      type: object
      oneOf:
        - $ref: '#/components/schemas/DuplicateEmailError'
        - $ref: '#/components/schemas/DuplicateNicknameError'

    SignUpArrayErrorResponse:
      type: array
      items :
        anyOf:
          - $ref: '#/components/schemas/DuplicateEmailError'
          - $ref: '#/components/schemas/DuplicateNicknameError'

    SignUpDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        nickname:
          type: string

    SignUpResponseDto:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 201
        message:
          type: string
          example: 정상적으로 로그인하였습니다.

    CreatePostDto:
      type: object
      properties:
        title:
          type : string
        contents:
          type : string
        displayLevel:
          type : string
        price :
          type : integer
        userId:
          type : integer
        
    ReadPostDto:
      type : object
      properties:
        userId:
          type : integer
    
    UpdatePostDto:
      type: object
      properties:
        title:
          type : string
        contents:
          type : string
        displayLevel:
          type : string
        price :
          type : integer
        userId:
          type : integer

    DeletePostDto:
      type: object
      properties:
        userId :
          type : integer
          example : 10

    LoginDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    Auth:
      type: object
      properties:
        nickname:
          type: string
        userId:
          type: integer
          format: int32
          example: 20
    
    LoginResponseDto:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 정상적으로 로그인하였습니다.

        user:
          $ref: '#/components/schemas/Auth'
    
    CreatePostResponse:
      type: object
      properties:
        status :
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 포스트가 성공적으로 생성되었습니다.
        postId :
          type: integer
          format: int32
          example: 10

    ReadPostResponse:
      type: object
      properties:
        status :
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 포스트가 성공적으로 요청되었습니다.
        title:
          type: string
          example : 글 제목입니다.
        content:
          type: string
          example : 글 내용입니다.
        
    
    UpdatePostResponse:
      type: object
      properties:
        status :
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 수정 요청이 완료되었습니다.
    
    DeletePostResponse:
      type: object
      properties:
        status :
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 삭제 요청이 완료되었습니다.
    


    InvalidEmailError:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 40101
        message:
          type: string
          example: 존재하지 않는 이메일입니다.
        code:
          type: string
          example: "M001"


    InvalidPasswordError:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 40102
        message:
          type: string
          example: 비밀번호가 틀렸습니다.
        code:
          type: string
          example : "M002"


    NotFoundError:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 404
        message:
          type: string
        code:
          type: string
          example: "M004"


    DuplicateEmailError:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 40901
        message:
          type: string
          example: 중복된 이메일입니다.
        code:
          type: string
          example: "M010"
    

    DuplicateNicknameError:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 40902
        message:
          type: string
          example: 중복된 닉네임입니다.
        code:
          type: string
          example: "M011"
    

    DuplicateNicknameAndEmailError:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 40903
        message:
          type: string
          example: 중복된 닉네임, 이메일입니다.
        code:
          type: string
          example: "M011"